# Generated by Django 4.2.6 on 2023-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
    ]
