# Generated by Django 4.2.6 on 2023-10-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_address_zip_code_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
